<div class='span12 white-panel'>

	<h3>
		Forgot Password.
	</h3>
	
	
	<div class='row-fluid'>
		
		<form  method='post' action=''>		
		<?php
			if($this->err){
				echo "<div class='alert alert-error'>{$this->err}<button type='button' class='close' data-dismiss='alert'>&times;</button></div>";
			}
			if($this->msg){
				echo "<div class='alert alert-success'>{$this->msg}<button type='button' class='close' data-dismiss='alert'>&times;</button></div>";
			}
		?>
			<div class='muted'>You will receive an email with the reset link.</div>
			<br>
			<p>
			<input type="text" name='email' required placeholder="your email">	
			<br><br>
			<button type="submit" class="btn btn-primary"> Send Me Reset Link </button>
			</p>
			<hr>			
		</form>
		<a href='<?=HTTP.WWW_ROOT?>/login'>Back to login.</a>
	</div>

</div>

